Bandwith computation
membraneframework-labs/membrane_live pull request #157
Opened 2023-01-24 15:44 UTC by shuntrho

2023-01-31 10:36 UTC, Rados13 approved these changes

2023-02-23 17:18 UTC, Karolk99 requested changes

2023-02-23 17:18 UTC, Karolk99 commented on test/membrane_live_web/controllers/hls_controller_test.exs
> +      Process.sleep(50)
why do we need process sleep?

2023-02-24 08:45 UTC, shuntrho commented on test/membrane_live_web/controllers/hls_controller_test.exs
> +      Process.sleep(50)
Tbh, I don't know. Removed this line 👌🏽

2023-02-24 08:46 UTC, shuntrho commented on lib/membrane_live/event.ex
> -        {peer_id, _peer_channel_pid} = result
This line caused errors in the tests. The `result` was nil.

2023-02-24 09:24 UTC, Karolk99 approved these changes

2023-03-02 09:46 UTC, Rados13 approved these changes

2023-03-02 11:02 UTC, merged