Update to core 0.11
membraneframework-labs/membrane_live pull request #159
Opened 2023-02-03 13:50 UTC by Karolk99

2023-02-10 06:25 UTC, Rados13 reviewed
Everything looks good but there is no branch with the name `live-dev-update-core` in membrane_rtc_engine repository.

2023-02-14 10:37 UTC, Rados13 requested changes
There are some issues with dependencies.
```
** (Membrane.ParentError) Child module "Membrane.AudioFiller" is neither Membrane Element nor Bin.
Make sure that given module is the right one, implements proper behaviour
and all needed dependencies are properly specified in the Mixfile.
```

2023-02-14 13:18 UTC, Karolk99 commented
There was a slight change in rtc engine with the return value when rtc engine was spawned which caused errors.

2023-02-15 09:55 UTC, Rados13 approved these changes

2023-02-15 14:56 UTC, merged