Fix/main presenter
membraneframework-labs/membrane_live pull request #181
Opened 2023-04-24 11:13 UTC by blazpie

When the main presenter leaves a event without beeing unselected moderator can now select new main presenter. Also menu option "set as main presenter" is visible in side menu for moderator and gives moderator an option to choose new main presenter from basic presenters too

2023-04-25 08:25 UTC, Karolk99 requested changes

2023-04-25 08:25 UTC, Karolk99 commented on lib/membrane_live_web/channels/event_channel.ex
> +      end
I think we also have to remove him from the regular presenters list and from rtc_engine peers. LIke in `handle_in("presenter_remove"....)`

2023-04-25 09:44 UTC, blazpie commented on assets/js/components/event/Sidebar.tsx
> +            </MenuItem>
This is what I also thought about when writing it, but it requires some new logic as the moderator's browser doesn't know who is the main presenter now. I can do it, but maybe there is something more urgent.

BTW. there are some other things I'd change in this menu also.

2023-05-09 14:03 UTC, Karolk99 requested changes

2023-05-15 14:19 UTC, Karolk99 approved these changes

2023-05-26 10:05 UTC, merged