Live compositor
membraneframework-labs/membrane_live pull request #189
Opened 2023-07-12 13:15 UTC by Karolk99

2023-07-12 14:28 UTC, roznawsk requested changes

2023-07-12 14:31 UTC, Karolk99 commented on lib/membrane_live/event.ex
> +    Engine.terminate(state.rtc_engine, asynchronous?: true)
But sure I can make it raise if something go wrong

2023-07-13 11:48 UTC, roznawsk submitted a review, later dismissed
👍🏽

2023-07-13 11:48 UTC, roznawsk commented on lib/membrane_live/event.ex
> +        "[Event: #{state.event_id}] RTC Engine was forced kill. This can cause some problems with plaiyng HLS playlist."
```suggestion
        "[Event: #{state.event_id}] RTC Engine was forced kill. This can cause some problems with playing HLS playlist."
```

2023-07-13 13:49 UTC, merged